[package]
name = "arm_vcpu"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.21"
spin = "0.9"

aarch64-cpu = "10.0"
tock-registers = "0.9"
numeric-enum-macro = "0.2"

axerrno = "0.1.0"
percpu = { version = "0.2.0", features = ["arm-el2"] }

axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git" }
axdevice_base = { git = "https://github.com/arceos-hypervisor/axdevice_crates.git" }
axvisor_api = { git = "https://github.com/arceos-hypervisor/axvisor_api.git" }
