[package]
name = "arm_vcpu"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.21"
spin = "0.9"

aarch64-cpu = "9.3"
tock-registers = "0.8"
numeric-enum-macro = "0.2"

axerrno = "0.1.0"
percpu = { version = "0.2.0", features = ["arm-el2"] }
aarch64_sysreg = "0.1.1"

axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git" }
